# Generated by Django 3.0.4 on 2022-03-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_categoria', '0002_auto_20220223_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado '),
        ),
    ]
