X
	XXXXXXXXXXXXXX     XXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX     XXXXXXXX XXXXXX XXXXXXXXXXX
                XXXXXXXXXXXXXXX    XXX XX XXXXXXXXXXX XXXXXXXXXXXX
                XXXXXXXXXXXXXX     XXXXXXX XXXX XXXXXXXXXX XX XXXX XXXXX XXXX
                XXXXXXXX           XXXXXXXXXX XXXXXXXXX XXX XXXXXXX XX XXXXX XX XX XXXXX XX XXXXXXX XXXXXXXXXXX
                XXXXXXXXXXXXX      XXXXXXXXXX XXXXXXXXX XXX X XX X XX XX XXXXX XX X XXXXXXXXXXX
                XXXXXXXXXXXXXXXX   XXXXXXXXXX XX XX XXXXX XX XXXXX XXXXXXXXXXXX
                XXXXXXXXXXXXXXX    XXX
                XXXXXXXXXX         XXXXXXXXXX
                XXXXXXX            XXX
                XXXXXXXXXXXXXXXXX  XXXX
                XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXXXXXXXXX X
                    XXXXXXXXX    XXXXXXXXXX
                    XXXXXXXX     XXXXXXXXX
                    XXXXXXXX     XXXXXXXXXXXX
                    XXXXXXXXXXXX XXXXXXXXXX
                XX
                XXXXXXXX X
                    XXXXXXXXXXXXXXXXX  XX XXXXXXX XXXX XXXXXXX XX XXXXXXX XX XXXXXX XXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXX XX XXXXXXX XXXX XXXXXXX XX XXXXXXX XX XXXXXX XXXXXXXXXXXX
                XX
                XXXXXXXXXX X
                    XXXXXXX XXXXXXXXX
                    XXXXXXXXX XXXXXXXXXXXXX
                X
X