# Generated by Django 3.0.4 on 2022-04-04 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dieta_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aniodieta',
            options={'ordering': ['id'], 'verbose_name': 'AnioDieta', 'verbose_name_plural': 'AniosDietas'},
        ),
        migrations.AlterModelOptions(
            name='detallediadieta',
            options={'ordering': ['id'], 'verbose_name': '4. Detalle del dia dieta', 'verbose_name_plural': '4. Detalle del dia dietas'},
        ),
        migrations.AlterField(
            model_name='diadietaregistro',
            name='mes_dieta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_dieta_reg.MesDieta', verbose_name='Mes de Dieta'),
        ),
        migrations.AlterModelTable(
            name='aniodieta',
            table='db_anio_dieta',
        ),
        migrations.AlterModelTable(
            name='detallediadieta',
            table='db_dia_dieta_detalle',
        ),
    ]
