# Generated by Django 3.0.4 on 2022-04-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dieta_reg', '0002_auto_20220404_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diadietaregistro',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Dieta'),
        ),
        migrations.AlterField(
            model_name='diadietaregistro',
            name='mes_dieta',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app_dieta_reg.MesDieta', verbose_name='Mes de Dieta'),
            preserve_default=False,
        ),
    ]
