# Generated by Django 3.0.4 on 2022-02-22 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_categoria', '0001_initial'),
        ('app_reg_empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Stock')),
                ('nombre_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reg_empresa.Empresa', verbose_name='Empresa')),
                ('nombre_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_categoria.Producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Stock Total',
                'verbose_name_plural': 'Stocks Totales',
                'db_table': 'stock_total',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, default='INGRESO', max_length=8, null=True)),
                ('piscinas', models.CharField(blank=True, default='Insumo para todas las piscinas', max_length=250, null=True)),
                ('cantidad_usar', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Cantidad en ')),
                ('cantidad_ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Cantidad de Ingreso en ')),
                ('cantidad_egreso', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Cantidad de Egreso en ')),
                ('fecha_ingreso', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Registro ')),
                ('numero_guia', models.CharField(blank=True, max_length=250, null=True, verbose_name='Numero Guia o Descripción ')),
                ('responsable_ingreso', models.CharField(blank=True, max_length=250, null=True, verbose_name='Persona Responsable ')),
                ('producto_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_detalle_stock.Total_Stock', verbose_name='Producto Stock ')),
            ],
            options={
                'verbose_name': 'Kardex',
                'verbose_name_plural': 'Kardexs',
                'db_table': 'stock_prod',
                'ordering': ['id'],
            },
        ),
    ]
