# Generated by Django 3.0.4 on 2022-03-05 20:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_detalle_stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detProducto_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Registro ')),
                ('numero_guia', models.CharField(blank=True, max_length=250, null=True, verbose_name='Numero Guia o Descripción ')),
                ('responsable_ingreso', models.CharField(blank=True, max_length=250, null=True, verbose_name='Persona Responsable ')),
                ('prod_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_detalle_stock.Producto_Stock')),
                ('tot_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_detalle_stock.Total_Stock')),
            ],
            options={
                'verbose_name': 'Prod Stock',
                'verbose_name_plural': 'Prod Stocks',
                'db_table': 'detProd_Stock',
                'ordering': ['id'],
            },
        ),
    ]
