# Generated by Django 3.0.4 on 2022-03-05 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_detalle_stock', '0002_detproducto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'InvoiceStock',
                'verbose_name_plural': 'InvoiceStock',
                'db_table': 'invoiceStock',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='producto_stock',
            name='invoice_stock',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app_detalle_stock.InvoiceStock', verbose_name='Factura'),
            preserve_default=False,
        ),
    ]
