# Generated by Django 3.0.4 on 2022-03-05 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_detalle_stock', '0003_auto_20220305_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicestock',
            name='fecha_ingreso',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Registro '),
        ),
        migrations.AddField(
            model_name='invoicestock',
            name='numero_guia',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Numero Guia o Descripción '),
        ),
        migrations.AddField(
            model_name='invoicestock',
            name='responsable_ingreso',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Persona Responsable '),
        ),
    ]
