# Generated by Django 3.0.4 on 2022-03-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_detalle_stock', '0004_auto_20220305_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_stock',
            name='invoice_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_detalle_stock.InvoiceStock', verbose_name='Factura'),
        ),
    ]
