# Generated by Django 3.0.4 on 2022-02-22 15:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre Empresa')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='RUC')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('siglas', models.CharField(max_length=150, unique=True, verbose_name='Siglas')),
                ('aperturada', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha Apertura')),
                ('actividad', models.CharField(max_length=150, verbose_name='Actividad')),
                ('estado', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo_comp/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'tb_empresa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Piscinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('numero', models.CharField(max_length=150, unique=True, verbose_name='Número de Piscina')),
                ('hect', models.CharField(max_length=150, verbose_name='Hectáreas de Dimensiones')),
                ('pis', models.BooleanField(default=True, verbose_name='Piscina')),
                ('prec', models.BooleanField(default=True, verbose_name='Precria')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reg_empresa.Empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Piscina',
                'verbose_name_plural': 'Piscinas',
                'db_table': 'tb_piscina',
                'ordering': ['id'],
            },
        ),
    ]
