# Generated by Django 3.0.4 on 2022-02-23 16:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reg_empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='actividad',
            field=models.CharField(max_length=150, verbose_name='Actividad '),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='aperturada',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de Apertura '),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(max_length=150, verbose_name='Direccion '),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre Empresa '),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(max_length=13, unique=True, verbose_name='RUC '),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='siglas',
            field=models.CharField(max_length=150, unique=True, verbose_name='Siglas '),
        ),
        migrations.AlterField(
            model_name='piscinas',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_reg_empresa.Empresa', verbose_name='Empresa '),
        ),
        migrations.AlterField(
            model_name='piscinas',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado '),
        ),
        migrations.AlterField(
            model_name='piscinas',
            name='numero',
            field=models.CharField(max_length=150, unique=True, verbose_name='Número de Piscina '),
        ),
        migrations.AlterField(
            model_name='piscinas',
            name='orden',
            field=models.IntegerField(default=0, verbose_name='Orden de las Piscinas '),
        ),
        migrations.AlterField(
            model_name='piscinas',
            name='pis',
            field=models.BooleanField(default=True, verbose_name='Piscina '),
        ),
        migrations.AlterField(
            model_name='piscinas',
            name='prec',
            field=models.BooleanField(default=True, verbose_name='Precria '),
        ),
    ]
